# Generated by Django 5.2.4 on 2025-08-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_name_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
