# Generated by Django 5.2.4 on 2025-08-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview_order_item_productreview_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='stock_quantity',
        ),
    ]
